version: "3.9"

services:
  postgres_db:
    image: postgres:latest
    container_name: mysite_postgres
    env_file:
      - .env
    volumes:
      - db_data_volume:/var/lib/postgresql/data

  app:
    build:
      context: ./
    container_name: mysite_app
    env_file:
      - .env
    volumes:
      - static_volume:/mysite/static
    depends_on:
      - postgres_db
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"


  nginx:
    image: nginx:latest
    container_name: mysite_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    depends_on:
      - app

volumes:
  static_volume:
  db_data_volume: